### ISSUE TITLE
different page_id and file_id?

### ISSUE THREAD

**Issue by nandac06** [minimaxir/facebook-page-post-scraper#109]
what different between page_id at get_fb_post_page with file_id at get_fb_comments_from_fb ?
I want to crawl page fb and the comments on that page and i dont understand how to combine that.
When i run get_fb_comments script i get error like this.
Traceback (most recent call last):
  File "get_fb_comments_from_fb.py", line 232, in <module>
    scrapeFacebookPageFeedComments(file_id, access_token)
  File "get_fb_comments_from_fb.py", line 187, in scrapeFacebookPageFeedComments
    sub_comment, status['status_id'], comment['id'])
  File "get_fb_comments_from_fb.py", line 93, in processFacebookComment
    comment_author = unicode_decode(comment['from']['name'])
KeyError: 'from'

**Comment by rlorenz123** [comment]
I am having the same problem with the same error message.
