### ISSUE TITLE
HTTP error 400

### ISSUE THREAD

**Issue by jeonjaehyuk** [minimaxir/facebook-page-post-scraper#23]
Hi i found your repository from some blogger

And he write like this (he modify your code like this)

But it is not working and  HTTP erorr 400
(HTTP Error 400: Bad Request
^CTraceback (most recent call last):
  File "get_fb_test.py", line 152, in <module>
    wan_data, num = fetch_feed()
  File "get_fb_test.py", line 104, in fetch_feed
    one_json = getFacebookPageFeedData(page_id, access_token, since, until)
  File "get_fb_test.py", line 32, in getFacebookPageFeedData
    data = json.loads(request_until_suceed(url))
  File "get_fb_test.py", line 47, in request_until_suceed
    time.sleep(5)
)

Also i did put my app_id app_secret  and page id, since and until

Can you help me?

Belowing is that bloger's code
=========================================================
# -*- coding: euc-kr -*-

import json;
import csv
import datetime;
import time;
import urllib2

# dizwe
app_id = " "
app_secret = " "
access_token = app_id + "|" + app_secret

# advaced information
def getFacebookPageFeedData(page_id, access_token, since, unitl):
    # construct the URL string
    base = "https://graph.facebook.com"
    node = "/" + page_id + "/feed"
    parameters1 = "/?fields=message,created_time,likes.limit(1).summary(true),"
    # -b - cf -  comments.fields(message,parent).summary(true) (- cannot see replies)
    # -b - changed if you add parent in  filter(stream){message,id,"parent"}, you can see parent
    parameters2 = "comments.summary(true).filter(stream){message}"
    time = "&since=%s&until=%s" % (since, until)
    access = "&access_token=%s" % access_token
    url = base + node + parameters1 + parameters2 + time + access
    print url  ###DEL

    # retrieve data
    data = json.loads(request_until_suceed(url))

    return data

def request_until_suceed(url):
    req = urllib2.Request(url)
    success = False
    while success is False:
        try:
            response = urllib2.urlopen(req)
            if response.getcode() == 200:
                success = True
        except Exception, e:
            print e  # wnat to know what error it is
            time.sleep(5)
            print "Error for url %s : %s" % (url, datetime.datetime.now())

    return response.read()

def fetch_comments(status, status_message):
    com = status_message
    page = ' ' if 'comments' not in status.keys() else status['comments']
    # print json.dumps(page, indent=4, sort_keys=True) ###DELETE
    j = 0  ################DELETE
    while True:  # until no more next
        try:

            comments = ' ' if 'comments' not in status.keys() else page['data']
            ##########until no more comment in page
            i = 0
            while True:
                try:
                    # append message and comments using :]
                    # http://me2.do/5ZryZrRd(not considering codec error)
                    com = com + ' :] ' + comments[i]['message'].encode('euc-kr', 'replace')

                    i = i + 1
                except:
                    break
                    ############

            # get next page comment json
            nex = json.loads(request_until_suceed(page['paging']['next']))
            page = nex
            j = j + 1;
            print "   %d th comment in one status" % j
            # print json.dumps(page, indent=4, sort_keys=True)###DELETE

        except KeyError:  # no more next
            break

    return com

def processFacebookPageFeedStatus(status):
    # kyes is the name of the list
    status_message = ' ' if 'message' not in status.keys() else status['message'].encode('euc-kr', 'replace')
    # time(http://devanix.tistory.com/306)
    status_published = datetime.datetime.strptime(status['created_time'], '%Y-%m-%dT%H:%M:%S+0000')
    status_published = status_published + datetime.timedelta(hours=+9)
    status_published = status_published.strftime('%Y-%m-%d %H:%M:%S')

    num_likes = 0 if 'likes' not in status.keys() else status['likes']['summary']['total_count']
    num_comments = 0 if 'comments' not in status.keys() else status['comments']['summary']['total_count']
    com = fetch_comments(status, status_message)

    return (status_message, status_published, num_likes, com)

def fetch_feed():
    one_json = getFacebookPageFeedData(page_id, access_token, since, until)
    wan_data = []
    j = 0
    i = 0
    num = 0
    while True:
        try:
            test_status = one_json["data"][i]
            processed_test_status = processFacebookPageFeedStatus(test_status)
            wan_data.append(list(processed_test_status))
            print "%d th status in %d" % (i, num)
            i = i + 1
            num = num + 1
        except Exception, e:
            print e
            try:
                next_url = one_json["paging"]["next"]  # next url
                print next_url
                j = j + 1
                print "----"
                # print j #FOR CHECK
                one_json = json.loads(request_until_suceed(next_url))
                i = 0
                continue
            except KeyError:
                print 'End of Document'
                break

    return wan_data, num

#######CSV######
def write_csv(wan_data, num):
    with open('data %s %s.csv' % (since, until), 'wb') as file:  #
        w = csv.writer(file)
        w.writerow(['content_names', 'content_dates', 'content_hits', 'content_coms'])
        for i in range(num):
            w.writerow([i, wan_data[i][1], wan_data[i][2], wan_data[i][3]])
            # w.writerow([wan_data[6][0],wan_data[6][1],wan_data[6][2],wan_data[6][3]])

# dizwe
########BASIC########
# bamboo = 413238928809895
page_id = " "
since = " "
until = " "
######################
wan_data, num = fetch_feed()
write_csv(wan_data, num)

**Comment by baditaflorin** [comment]
same problem here, do you have any idea if facebook did some modification to the algorithm ?

**Comment by danbenporat** [comment]
@baditaflorin I had the same issue, resolved by resetting my auth token. FB released v2.8 on October 5th, guessing it is related.

**Comment by Techarvi** [comment]
Took me a while to figure out, but a cause might be that you need a user token, rather than an App token. If it's a page that has restrictions (such as age, location, etc) you'll need a User token for the code to work

**Comment by rougetimelord** [comment]
Take the logged URL and use it in chrome and it'll give you the actual error, I'll bet that it's a badly formed token.

**Comment by longle255** [comment]
got the same error today. I guess that was problem with python/urllib2. I was able to run same script on MacOS, but not on Ubuntu. On ubuntu it always throws HTTP Error 400: Bad Request

If I copy the url and open on my browser, it still works.

**Comment by hemangpar** [comment]
Same HTTP 400 : Bad request
its showing error for URL, Can anyone help ? And yeah one doubt , the facebook page which i want to scrap, do i need to give it full URL or just the name of page ? For example the page name is "MR A".  So in page id it should be like "https://www.facebook.com/MR A/" or just "MR A" ??
