### ISSUE TITLE
ability to handle dates that are before 1900

### ISSUE THREAD

**Issue by baditaflorin** [minimaxir/facebook-page-post-scraper#24]
Because some pages are using the set date post to the year when the brand was created, like the page pnl.ro

Traceback (most recent call last):
  File "romania_get_fb_posts_fb_page.py", line 195, in <module>
    scrapeFacebookPageFeedStatus(page_id, access_token)
  File "romania_get_fb_posts_fb_page.py", line 174, in scrapeFacebookPageFeedStatus
    access_token))
  File "romania_get_fb_posts_fb_page.py", line 107, in processFacebookPageFeedStatus
    '%Y-%m-%d %H:%M:%S')  # best time format for spreadsheet programs
ValueError: year=1875 is before 1900; the datetime strftime() methods require year >= 1900

**Comment by minimaxir** [comment]
In the case of the page you mention, it is a [milestone](https://www.facebook.com/181375448581167/posts/363180033734040/), not a typical post with expected engagement.

Not To Be Fixed.
