### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by cdhit** [minimaxir/facebook-page-post-scraper#49]
17200 Statuses Processed: 2017-05-19 21:59:50.230000

```
Traceback (most recent call last):
  File "C:/xxxxx/facebook-page-post-scraper/get_fb_posts_fb_group.py", line 187, in <module>
    scrapeFacebookPageFeedStatus(group_id, access_token)
  File "C:/xxxxx/facebook-page-post-scraper/get_fb_posts_fb_group.py", line 183, in scrapeFacebookPageFeedStatus
    (num_processed, datetime.datetime.now() - scrape_starttime)))
IndexError: tuple index out of range
```

**Comment by paladini** [comment]
Same here :/

**Comment by minimaxir** [comment]
That line only triggers when the script is done, so you have not lost any data.

Looking at a fix.

**Comment by paladini** [comment]
Hey @minimaxir , I've fix it by myself too. Just go to line 167 of get_fb_posts_fb_page.py and change this code:

```
print("\nDone!\n{} Statuses Processed in {}".format(
              (num_processed, datetime.datetime.now() - scrape_starttime)))
```

For this one:
```
        print("\nDone!\n{} Statuses Processed in {}".format(
              num_processed, (datetime.datetime.now() - scrape_starttime)))
```

Hope this helps you :)

**Comment by minimaxir** [comment]
...well I feel silly. Should have caught that during testing.

**Comment by paladini** [comment]
Thanks for the fix! I think you can close this issue now.
