### ISSUE TITLE
ERROR : The JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by Sakelariev** [minimaxir/facebook-page-post-scraper#77]
When I tried to test the get_fb_posts_fb_page.py I get this error : 

Traceback (most recent call last):
  File "get_fb_posts_fb_page.py", line 184, in <module>
    scrapeFacebookPageFeedStatus(page_id, access_token, since_date, until_date)
  File "get_fb_posts_fb_page.py", line 154, in scrapeFacebookPageFeedStatus
    statuses = json.loads(request_until_succeed(url))
  File "/Users/user/anaconda3/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

Does anyone know what is causing it?

**Comment by Sakelariev** [comment]
I seem to have missed an earlier Issue, where the problem is resolved. Sorry!
