### ISSUE TITLE
HTTP Error 400: Bad request (Object ID not found)

### ISSUE THREAD

**Issue by Thunderbolt1989** [minimaxir/facebook-page-post-scraper#82]
Hi, 

I'm trying to also use the scraper for some pages and facing similar error problems, from hitting HTTP Error 400: Bad Request.

Here's one example:
page_id = TigerBeer.SG

When I try to access the full URL itself, I get this:
{
   "error": {
      "message": "Unsupported get request. Object with ID 'TigerBeer.SG' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
      "type": "GraphMethodException",
      "code": 100,
      "error_subcode": 33,
      "fbtrace_id": "EKPM8lx5jXI"
   }
}

This error is similar to some of the other pages I am trying to scrape. How do I determine what exactly is the reason behind not being able to scrape (i.e. missing permissions or does not support this operation)

Thank you!

**Comment by rudolphos** [comment]
I'm also having similar error

```
Scraping ...Facebook Group: 2017-...

HTTP Error 400: Bad Request
^CTraceback (most recent call last):
  File "get_fb_posts_fb_group.py", line 27, in request_until_succeed
    response = urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by gielk** [comment]
Any solution ?

**Comment by Thunderbolt1989** [comment]
Not yet I believe, I"m still unable to trace to what is causing the error for mine

**Comment by JaeguKim** [comment]
I think access_token might be expired. In my case, my facebook account was deactivated after few days to run this code.

**Comment by rogerdohe** [comment]
I have the same mistake, ¿has someone solved it? (HTTP Error 400: Bad Request)

**Comment by wachmann** [comment]
I had a similar problem when scraping groups and I found this on the Facebook Developers site: "As of April 4, 2018, this node and its edges return empty data sets for GET operations unless the calling app has gone through App Review. Please see the Groups API section of the Breaking Changes changelog for more information."
