### ISSUE TITLE
Type error runing page-post-scraper

### ISSUE THREAD

**Issue by davideastside** [minimaxir/facebook-page-post-scraper#86]
Traceback (most recent call last):
  File "fb.py", line 184, in <module>
    scrapeFacebookPageFeedStatus(page_id, access_token, since_date, until_date)
  File "fb.py", line 154, in scrapeFacebookPageFeedStatus
    statuses = json.loads(request_until_succeed(url))
  File "C:\Users\DaveM\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 312, in loadss.__class__.__name__))
**TypeError: the JSON object must be str, not 'bytes'**

**Comment by leftyveggie** [comment]
I have also got this problem - did you solve the issue?
